FROM python:3.6-alpine

ADD . /app
WORKDIR /app
RUN pip install -r requirements.txt

ENV FLASK_APP /app/frontend.py
ENV FLASK_ENV development

CMD ["flask", "run"]
CMD ["gunicorn", "-b", ":8000", "frontend:app"]
