FROM python:3.6-alpine

RUN apk add docker

ADD . /app
WORKDIR /app
RUN pip install -r requirements.txt

ENV FLASK_APP /app/manager.py
ENV FLASK_ENV development

CMD ["gunicorn", "-b", ":8001", "manager:app"]
